### ISSUE TITLE
loopback-component-auto-migrate-done is not resolved

### ISSUE THREAD

**Issue by akkonrad** [snowyu/loopback-component-auto-migrate.js#11]
In my setup this promise is never resolved:

**./server/component-config.json:**
```
{
  "loopback-component-auto-migrate": {
    "enabled": true,
    "raiseError": true,
    "migration": "auto-update"
  }
}
```

**./server/component-config.testing.json**
```
{
  "loopback-component-auto-migrate": {
    "enabled": true,
    "raiseError": false,
    "migration": "auto-migrate"
  }
}
```
**./server/boot/file1.js**
```
module.exports = function (app) {
    app.get('loopback-component-auto-migrate-done')
      .then((result) => {
        console.log('migration done (file1) - this never shows up in logs');
      });
}
```
**./server/boot/file1.js**
```
module.exports = function (app) {
    app.get('loopback-component-auto-migrate-done')
      .then((result) => {
        console.log('migration done (file2) - this never shows up in logs');
      });
}
```

command:
`export DEBUG=loopback:component:autoMigrate:*; export NODE_ENV=testing; npm start`

loopback debug (one line, nothing else):
```
  loopback:component:autoMigrate:main initializing component +0ms
```

___

When there is no database or it's empty, collections are created correctly, but that promise is never resolved.

Edit: I've found that it's happening only when this module is also enabled and configured:
https://github.com/kolach/loopback-component-cloudinary

**Comment by snowyu** [comment]
Does the auto-migrate task executed or not? If not , which means the loopback can not process promise for some reason or the process be stopped via other internal error?

**Comment by snowyu** [comment]
Do you skip these loopback-component-cloudinary model?

**Comment by snowyu** [comment]
Or just set only one model to test migration.

**Comment by akkonrad** [comment]
I skip the loopback-component-cloudinary model and it worked, that's why I introduced this [PR](https://github.com/snowyu/loopback-component-auto-migrate.js/pull/12)
Now it's all fine, you can close this thread, thank you
