### ISSUE TITLE
Problems to create tables on Windows (Solved)

### ISSUE THREAD

**Issue by andenis** [snowyu/loopback-component-auto-migrate.js#13]
Hi @snowyu, 
I'm new using Node, I created a new Loopback 3 project, and I use PostgreSQL 10 Database.
I followed the detailed steps: 
1 - npm install --save loopback-component-auto-migrate
2 - create the file: component-config.json 
3- added the models: "models": ["User","AccessToken", "ACL", "RoleMapping", "Role", "Country"]

I don't understand how to configure the Automatically and/or Manual the component in my loopback project.

If I run "npm start" the tables are not created in my PostgreSQL database.

Maybe I'm missing something, for example I don't have Grunt configured in my project, I do not know if any of this is necessary.

Thank you very much for your time and this component, it is very useful.

Regards,
Andres

**Comment by snowyu** [comment]
missing `migration` config, the default is update only(don't create)  read the doc carefully.

**Comment by andenis** [comment]
yes,
{
    "loopback-component-auto-migrate": {
        "enabled": true,
        "raiseError": false,
        "migration": "auto-migrate",
        "models": [
            "User",
            "AccessToken",
            "ACL",
            "RoleMapping",
            "Role",
            "Country"
        ],
        "fixtures": "./test/fixtures/"
    }
}
but don't created when I execute "npm start"

**Comment by snowyu** [comment]
What's your debug output?

`DEBUG=loopback:component:autoMigrate:* npm start`

**Comment by andenis** [comment]
I running on Windows 10. The postgreSQL tables are empty.
I Attached my project. [api.zip](https://github.com/snowyu/loopback-component-auto-migrate.js/files/2328617/api.zip)

PS C:\GIT\vivomotor\api> set DEBUG=loopback:component:autoMigrate:*
PS C:\GIT\vivomotor\api> npm start

> api@1.0.0 start C:\GIT\vivomotor\api
> node .

Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer

**Comment by snowyu** [comment]
No any output?

it seems that the component is not enabled.
r u sure install it correctly?

try run it manually. 

`node node_modules/.bin/slc-migrate`

**Comment by andenis** [comment]
When I execute: node node_modules/.bin/slc-migrate 
It have a error:
PS C:\GIT\vivomotor\api> node node_modules/.bin/slc-migrate
C:\GIT\vivomotor\api\node_modules\.bin\slc-migrate:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)

---------------------------------------------------------------------------
Packages installed:
"dependencies": {
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^3.10.0",
    "loopback": "^3.19.0",
    "loopback-boot": "^2.6.5",
    **"loopback-component-auto-migrate": "^0.4.0",**
    "loopback-component-explorer": "^6.0.0",
    "loopback-connector-postgresql": "^2.9.0",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^3.0.0"
  },
  "devDependencies": {
    "eslint": "^3.19.0",
    "eslint-config-google": "^0.9.1",
    "eslint-config-loopback": "^8.0.0"
  },

Please check the project: https://github.com/snowyu/loopback-component-auto-migrate.js/files/2328617/api.zip

**Comment by snowyu** [comment]
Oh, It's a windows bug. just run `node  node_modules/loopback-component-auto-migrate/bin/migrate.js` directly.

**Comment by andenis** [comment]
@snowyu , works fine
PS C:\GIT\vivomotor\api> node node_modules/loopback-component-auto-migrate/bin/migrate.js
Migrate database: C:\GIT\vivomotor\api\server\data
autoMigrate successful.

Thanks!
and Thank you very much for the component, facilitate the use of loopback.
